import random

# ----- DRAGON MOOD -----
moodoftheday = [
    "Aggressively affectionate",
    "Ready to fight the moon",
    "Sleepy but dangerous",
    "Emotionally attached to shiny objects",
    "Hissing at everyone for no reason",
    "Crying over something tiny",
    "Overconfident and underprepared",
    "Refusing to leave nest",
    "Causing problems on purpose",
    "Too much energy at 3am",
    "Deeply offended by existence",
    "Acts tough, secretly wants cuddles",
    "Hovering ominously in doorways",
    "One inconvenience away from arson",
    "Stealing snacks and denying it",
    "Wants attention but bites if given",
    "Trying to impress someone badly",
    "Existential crisis on rooftop",
    "Ferally protective of friends",
    "Dramatic sighing all day",
    "Obsessed with one random thing",
    "Will absolutely make things worse",
    "Purring like an engine",
    "Avoiding responsibilities creatively",
    "Dangerously curious",
    "Emotionally unstable but funny about it",
    "Tiny problem feels world-ending",
    "Ready to commit crimes for fun",
    "Making reckless financial decisions",
    "Hoarding random junk again",
    "Flirting with danger literally",
    "Can and will climb everything",
    "Unreasonably smug",
    "Needs a nap immediately",
    "Thinks rules are suggestions",
    "Picking fights with objects",
    "Emotionally attached to a stray creature",
    "Paranoid but accidentally correct",
    "Acting mysterious for attention",
    "Hyperfixated on a new hobby",
    "Accidentally intimidating civilians",
    "Running entirely on caffeine",
    "Staring into the void dramatically",
    "Wants to disappear into the woods",
    "Too soft for this world today",
    "Threatening violence over mild inconvenience",
    "Mischief levels critically high",
    "Nesting instinct activated",
    "Collecting trinkets like a crow",
    "Pretending not to care",
    "Being suspiciously nice",
    "Starting emotional conversations at terrible times",
    "Would lose a fight to stairs today",
    "Absolutely forbidden from touching magic artifacts",
    "In desperate need of enrichment",
    "Trying to look cool and failing",
    "Ready to overthrow authority",
    "Sulking beautifully",
    "Overstimulated and growling about it",
    "Making everyone else's problems their problem",
    "No thoughts, only vibes",
    "Mildly haunted",
    "Acting like an abandoned wet cat",
    "Chronically yearning",
    "Violently protective of their blanket pile",
    "One compliment away from emotional collapse",
    "Too prideful to ask for help",
    "Emotionally support dragon mode",
    "Would absolutely eat something they shouldn't",
    "Unstable but sparkly",
    "Trying very hard not to bite someone",
    "Ready to run away and join a circus",
    "Overly competitive about everything",
    "Possessed by goblin energy",
    "Feels like screaming into the ocean",
    "Convinced they are the smartest in the room",
    "Actually just wants to be held",
    "Low battery warning",
    "Feral but in a charming way",
    "Suspiciously calm",
    "Full cryptid mode",
    "Emotionally damaged and dramatic about it"
]

def setup(bot):
    @bot.command()
    async def dragonmood(ctx):

        result = (
            f"-# Random dragon mood of the day \n"
            f"## {random.choice(moodoftheday)}\n"
        )

        await ctx.send(result)