import random

# ----- ASHARA -----
ashara = [
    "hiding in her nest",
    "stealing something for her nest",
    "purring loudly",
    "eating someones snacks",
    "sleeping peacefully",
    "demanding attention loudly",
    "cuddling with Nyx",
    "cuddling with Zevryn",
    "cuddling with Quin",
    "cuddling with Ithindril",
    "cuddling with Sevka",
    "cuddling with Silk",
    "cuddling with Ender",
    "holding Quin hostage",
    "holding Silk hostage",
    "holding Nyx hostage",
    "holding Zevryn hostage",
    "holding Sevka hostage",
    "holding Ender hostage",
    "grooming Ender",
    "grooming Zevryn",
    "grooming Nyx",
    "grooming Quin",
    "grooming Silk",
    "leaving little burn marks on the floor because she's bored",
    "blowing hot air on Nyx because they annoyed her",
    "blowing hot air on Silk because they annoyed her",
    "blowing hot air on Ender because they annoyed her",
    "blowing hot air on Quin because they annoyed her",
    "blowing hot air on Ithindril because they annoyed her",
    "blowing hot air on Zevryn because they annoyed her",
    "blowing hot air on Sevka because they annoyed her",
    "playing with Ithindril in  the warehouse and making so much mess and noise",
    "growling loudly in warning",
    "fussing with her nest",
    "growling and huffing because she's hangry",
    "setting minor fires that Sevka keeps puttinng out",
    "scraping her claws on the ground loudly to get attention",
    "rearranging her nest for the fifth time today",
    "dragging another blanket back to her nest",
    "adding something completely useless to her hoard",
    "guarding her nest like it contains priceless treasure",
    "trying to fit something far too large into her nest",
    "hiding shiny objects throughout the warehouse",
    "collecting things that smell like her family",
    "refusing to explain why she needed another pillow",
    "nesting aggressively",
    "burying herself under a mountain of blankets",
    "making dramatic noises until someone pays attention to her",
    "staring at someone until they acknowledge her existence",
    "following Zevryn around relentlessly",
    "following Quin around relentlessly",
    "following Ender around relentlessly",
    "following Silk around relentlessly",
    "demanding cuddles immediately",
    "flopping dramatically in the middle of the floor",
    "pretending she's being neglected",
    "making sad dragon noises despite receiving attention five minutes ago",
    "demanding to be told she's pretty",
    "shoving her head into someone's lap",
    "blocking a doorway until someone pets her",
    "sulking because everyone is busy",
    "curling protectively around one of the gang members",
    "sleeping on top of someone",
    "resting her head in someone's lap",
    "making happy little chirping sounds",
    "grooming her scales while purring",
    "trying to groom everyone in sight",
    "checking that everyone is where they're supposed to be",
    "making rounds to visit all her favorite people",
    "insisting on a group cuddle session",
    "nuzzling anyone within reach",
    "dozing with one eye open to watch over everyone",
    "patrolling the warehouse",
    "guarding a sleeping gang member",
    "standing watch near the entrance",
    "investigating a strange noise",
    "refusing to leave someone's side while they're upset",
    "protecting her hoard from imaginary threats",
    "warming up the warehouse because she felt like it",
    "accidentally scorching something with a sneeze",
    "making smoke rings out of boredom",
    "heating up everyone's drinks",
    "using her fire to toast snacks",
    "practicing controlled flames",
    "lighting candles around the warehouse",
    "making tiny harmless sparks dance across her claws",
    "showing off her fire breath",
    "making Sevka worry again",
    "knocking something over and pretending it wasn't her",
    "causing problems on purpose",
    "investigating something she absolutely shouldn't be touching",
    "attempting to help and somehow making things worse",
    "chasing Ithindril through the warehouse",
    "making enough noise for the entire city to hear",
    "playing with something expensive",
    "being far too pleased with herself",
    "creating a mess and immediately leaving",
    "sitting on something important",
    "looking for snacks",
    "stealing snacks from Quin",
    "stealing snacks from Ender",
    "stealing snacks from Silk",
    "eating enough food for three dragons",
    "waiting near the kitchen hopefully",
    "trying to convince someone she's starving",
    "hunting for hidden snacks",
    "accepting snacks as tribute",
    "trying to trade cuddles for food",
    "trying to squeeze into a space much too small for her",
    "arguing with an inanimate object",
    "chasing her own tail",
    "making dragon noises at absolutely nothing",
    "attempting to look intimidating while wrapped in blankets",
    "trying to convince everyone she's the boss",
    "having a staring contest with a wall",
    "waiting for someone to notice her latest achievement",
    "being offended for reasons only she understands",
    "holding the entire warehouse hostage with her cuteness"
]

def setup(bot):
    @bot.command()
    async def ash(ctx):

        result = (
            f"*Ashara is currently {random.choice(ashara)}*."
        )

        await ctx.send(result)
