import random

en = [
    "working on a new invention",
    "repairing damaged equipment",
    "writing code for a new project",
    "debugging a particularly stubborn issue",
    "testing a prototype",
    "upgrading the warehouse systems",
    "monitoring security feeds",
    "reviewing system diagnostics",
    "building something nobody else understands",
    "working on a secret project",
    "completely losing track of time while working",
    "focused so intensely on a project that he forgot lunch",
    "surrounded by tools and spare parts",
    "staring at a screen with intense concentration",
    "making notes for a future project",
    "researching new technology",
    "working through a list of ideas",
    "trying to solve a problem that nobody asked him to solve",
    "optimizing something that already worked fine",
    "disappearing into a project rabbit hole",
    "keeping everything running behind the scenes",
    "listening to Quin talk excitedly about something",
    "watching Ashara cause problems from a safe distance",
    "helping Sevka with a project",
    "having a discussion with Zevryn",
    "being dragged into one of Silk's schemes",
    "checking in on the gang",
    "helping someone with a personal project",
    "trying to be productive despite constant interruptions",
    "quietly enjoying everyone's company",
    "trying to work while Ithindril sits on his keyboard",
    "being used as a pillow by Ashara",
    "searching for a tool Ithindril stole",
    "attempting to recover stolen equipment",
    "trying to explain why electronics shouldn't be licked",
    "discovering that Ashara moved something important",
    "trying to keep dragons out of sensitive equipment",
    "accepting that the dragons own the warehouse now",
    "cleaning fur, scales, and feathers out of machinery",
    "reviewing reports of magical creature sightings",
    "designing equipment for rescue missions",
    "analyzing data from recent rescues",
    "maintaining rescue equipment",
    "testing tracking technology",
    "helping coordinate rescue efforts",
    "watching tech videos",
    "reading about new inventions",
    "drinking coffee while reviewing projects",
    "taking a rare break",
    "watching the warehouse activity from his workstation",
    "listening to music while he works",
    "enjoying a quiet moment",
    "organizing his workbench",
    "actually getting some sleep for once",
    "wondering where all his tools keep disappearing to",
    "finding yet another dragon in a place dragons shouldn't fit",
    "trying to remember what he originally started working on",
    "holding together a project with determination and optimism",
    "being interrupted for the seventh time today",
    "explaining the same thing for the third time",
    "pretending everything is under control",
    "wondering why every project becomes more complicated",
    "is asleep at his desk with a dragon curled on top of him",
    "has discovered a problem before it became a disaster",
    "has finally found the thing Ithindril stole three weeks ago",
    "is being aggressively supervised by Ashara",
    "is testing something that definitely won't explode (probably)",
    "is wondering how he became responsible for all of this",
    "listening to Quin excitedly talk about something",
    "watching Quin ramble with an affectionate smile",
    "helping Quin with one of his projects",
    "making something for Quin",
    "working while Quin sits nearby",
    "sharing snacks with Quin",
    "letting Quin steal his hoodie again",
    "finding feathers all over his workstation",
    "trying to work while Quin distracts him",
    "watching Quin reorganize their nest",
    "bringing Quin a snack",
    "checking in on Quin",
    "taking a break with Quin",
    "listening to one of Quin's songs",
    "helping Quin gather materials for their nest",
    "spending some quiet time with Quin",
    "answering one of Quin's many questions",
    "finding another shiny object Quin left on his desk",
    "wondering how Quin has this much energy",
    "carefully storing a feather Quin gifted him",
    "helping maintain their nest",
    "being gifted random treasures by Quin",
    "holding still while Quin fusses over him",
    "learning another one of Quin's songs",
    "collecting something he thinks Quin would like",
    "keeping an eye out for things Quin might want",
    "wondering how feathers keep ending up in his coffee",
    "being quietly fond of Quin's nesting habits",
    "watching Quin sunbathe",
    "trying to determine whether Quin is helping or causing problems",
    "following a trail of feathers and snacks to find Quin",
    "helping Quin out of a situation he got himself into",
    "being dragged into one of Quin's adventures",
    "finding Quin somewhere he definitely shouldn't be",
    "cleaning up after Quin's latest idea",
    "being recruited into a snack heist",
    "pretending not to encourage Quin's bad ideas",
    "failing to resist Quin's enthusiasm",
    "wondering what Quin and Ithindril are planning",
    "smiling at a message Quin sent him",
    "taking a picture because Quin looked adorable",
    "enjoying a peaceful moment with Quin",
    "watching Quin sleep",
    "quietly appreciating having Quin around",
    "letting Quin nap nearby while he works",
    "saving something because it reminded him of Quin",
    "thinking about a future project for Quin",
    "taking a rare break to spend time with Quin",
    "enjoying the sound of Quin singing nearby",
    "trying to remove feathers from sensitive equipment",
    "discovering Quin stole his lunch again",
    "finding Quin asleep somewhere unusual",
    "being stared at until he agrees to cuddle",
    "attempting to work while Quin sits directly on him",
    "trying to convince Quin not to adopt another creature",
    "accepting that Quin has claimed his chair",
    "discovering that Quin has reorganized something",
    "losing an argument to Quin's puppy-dog eyes",
    "quietly recording one of Quin's songs so he can listen to it later",
    "has built something specifically for Quin",
    "asleep with Quin curled up against him",
    "helping Quin build up their nest",
    "completely forgetting what he was working on because Quin distracted him",
    "watching Quin with the sort of expression that makes everyone else look away",
    "keeping one of Quin's feathers tucked safely in his pocket",
    "abandoning work entirely in favor of spending time with Quin"

]

def setup(bot):
    @bot.command()
    async def ender(ctx):

        result = (
            f"*Ender is currently {random.choice(en)}*."
        )

        await ctx.send(result)
