import random

# ----- ITHINDRIL -----
ithindril = [
    "hiding in her nest",
    "hiding in someones clothes",
    "sneaking around",
    "stealing something for her nest",
    "purring loudly",
    "eating someones snacks",
    "sleeping peacefully",
    "begging for attention",
    "demanding attention",
    "cuddling with Nyx",
    "cuddling with Zevryn",
    "cuddling with Quin",
    "cuddling with Ashara",
    "cuddling with Sevka",
    "cuddling with Silk",
    "cuddling with Ender",
    "licking Nyx's face",
    "licking Zevryn's face",
    "licking Quins's face",
    "dashing around the warehouse with a dose of the zoomies",
    "holding Quin hostage",
    "holding Silk hostage",
    "holding Nyx hostage",
    "holding Zevryn hostage",
    "holding Sevka hostage",
    "grooming Ashara",
    "grooming Zevryn",
    "grooming Nyx",
    "grooming Quin",
    "curled up on Silk's lap and refusing to budge",
    "celebrating stolen goods with Quin",
    "eating something she shouldn't be",
    "rearranging her tiny nest",
    "organizing her stolen treasures",
    "hiding shiny objects in her nest",
    "guarding a bottle cap like it's priceless treasure",
    "trying to drag something much larger than herself",
    "sorting her hoard into mysterious categories",
    "showing off her collection of stolen trinkets",
    "burying herself beneath blankets",
    "stealing soft things for her nest",
    "adding another treasure to her collection",
    "hiding somewhere nobody can find her",
    "sneaking through the warehouse vents",
    "watching everyone from a secret hiding place",
    "peeking out from behind a box",
    "attempting to remain unseen",
    "following someone without their knowledge",
    "eavesdropping on conversations",
    "lurking suspiciously",
    "spying on the gang from a high shelf",
    "hiding in plain sight",
    "perched on top of a shelf she definitely shouldn't be on",
    "climbing all over the warehouse",
    "sitting on top of a cupboard",
    "balancing somewhere precarious",
    "exploring the rafters",
    "trying to reach somewhere impossible",
    "climbing on Ashara",
    "using Zevryn as a climbing frame",
    "using Quin as a climbing frame",
    "sitting on Ender's shoulder",
    "curled up in someone's hood",
    "sleeping in someone's lap",
    "purring while being petted",
    "making tiny happy dragon noises",
    "following someone around",
    "nuzzling one of the gang members",
    "trying to cuddle everyone at once",
    "wrapped up in a blanket burrito",
    "sleeping on top of someone's chest",
    "insisting on being carried",
   "causing tiny amounts of chaos",
    "knocking things off a shelf",
    "running away with something important",
    "making trouble and loving every second of it",
    "investigating something dangerous",
    "getting into places she shouldn't be able to reach",
    "stealing a pen and refusing to return it",
    "being an absolute menace",
    "starting trouble and immediately disappearing",
    "creating problems for her own entertainment",
    "stealing snacks from Quin",
    "stealing snacks from Silk",
    "stealing snacks from Ender",
    "accepting snacks as tribute",
    "searching for snacks",
    "trying to convince everyone she's starving",
    "looking suspiciously at someone's lunch",
    "eating treats happily",
    "attempting to steal food right in front of everyone",
    "hoarding snacks for later",
    "helping Quin commit minor crimes",
    "celebrating a successful snack heist with Quin",
    "helping Quin hide evidence",
    "encouraging Quin's bad decisions",
    "sharing stolen snacks with Quin",
    "following Quin around like a tiny shadow",
    "looking for trouble with Quin",
    "participating in unauthorized adventures with Quin",
    "being a terrible influence on Quin",
    "being influenced by Quin's terrible ideas",
    "trying to groom Ashara's scales",
    "using Ashara as a heated bed",
    "curled up under Ashara's wing",
    "annoying Ashara for attention",
    "stealing things for Ashara's nest",
    "playing chase with Ashara",
    "sleeping beside Ashara",
    "trying to convince Ashara to play",
    "racing circles around Ashara",
    "bringing Ashara a shiny gift",
    "chasing her own tail",
    "making tiny growling noises",
    "trying to look intimidating",
    "showing off her tiny wings",
    "making excited chirping sounds",
    "pouncing on absolutely nothing",
    "zooming across the warehouse floor",
    "rolling onto her back for belly rubs",
    "trying to hunt a dust bunny",
    "being impossibly adorable",
    "sitting on Ender's keyboard",
    "helping Ender by making things significantly worse",
    "stealing components from Ender's workbench",
    "watching Ender work with intense curiosity",
    "napping on Ender's equipment",
    "accidentally submitting code by walking across a keyboard",
    "somehow trapped inside a hoodie",
    "has claimed a cardboard box as her kingdom",
    "asleep in the most inconvenient place imaginable",
    "starting a game of chase involving half the warehouse",
    "proudly carrying something larger than herself",
    "convincing Ashara to help with a heist",
    "receiving unlimited cuddles and has no intention of leaving",
    "mia \( has vanished with a suspiciously important item)\"
]


def setup(bot):
    @bot.command()
    async def ith(ctx):

        result = (
            f"*Ithindril is currently {random.choice(ithindril)}*."
        )

        await ctx.send(result)
