import random

aquiny = [
    "raiding someone's things for snacks",
    "curled up in one of his nests sleeping",
    "curled up in one of his nests eating snacks",
    "listening to Ender talk about tech",
    "reading up on the latest tech news",
    "gliding around the warehouse",
    "playing with Ithindril",
    "watching his monitoring system on his phone with a sad expression",
    "singing a threadsong - it's a beautiful sound",
    "singing a threadsong - it feels sad",
    "building a new nest out of random soft objects",
    "rearranging his nest for the third time today",
    "hoarding shiny objects 'just in case'",
    "tangled in blankets refusing to move",
    "half-asleep but still talking",
    "guarding his snack pile like it’s sacred",
    "humming softly while fixing his nest feathers",
    "falling asleep mid-sentence",
    "talking to three people at once and forgetting what he said",
    "pacing in circles while explaining something exciting",
    "interrupting himself with a new idea mid-sentence",
    "attempting five tasks and completing none",
    "chasing a thought like it physically ran away",
    "dramatically reenacting something that happened five minutes ago",
    "vibrating with excitement about literally nothing specific",
    "trying to teach someone something while also forgetting how it works",
    "humming old flock songs he barely remembers",
    "translating emotions into chirp patterns",
    "teaching one of the gang how windcalls 'feel'",
    "singing a threadsong to calm himself down",
    "sitting in the middle of everyone just listening happily",
    "trying to 'fix' someone’s mood by talking too much",
    "arguing playfully with Zevryn about snacks",
    "arguing playfully with Ender about snacks",
    "arguing playfully with Nyx about snacks",
    "bothering Sevka with endless questions",
    "helping Ithindril with something but getting distracted halfway",
    "helping Nyx with something but getting distracted halfway",
    "helping Ender with something but getting distracted halfway",
    "asking Ender what every button does",
    "clicking things he shouldn’t (again)",
    "getting distracted by glowing interfaces",
    "organizing data “based on vibes” instead of logic",
    "sitting quietly after overstimulation",
    "missing someone but not saying it",
    "replaying memories through threadsong",
    "resting his head against someone’s shoulder without speaking",
    "hiding snacks and forgetting where he put them",
    "insisting something happened that didn’t",
    "getting stuck in a nest and refusing to admit it",
    "trying to 'help' and making things worse",
    "declaring himself 'Snack Guardian' for the day",
    "curled up beside Ender while he works",
    "perched on the back of Ender's chair",
    "bringing Ender snacks",
    "stealing Ender's snacks",
    "watching Ender work on a project",
    "asking Ender approximately fifty questions",
    "helping Ender with a project",
    "attempting to help Ender with a project and making things worse",
    "bringing Ender random treasures he found",
    "preening Ender's hair",
    "stealing one of Ender's hoodies",
    "wearing one of Ender's hoodies",
    "waiting for Ender to take a break",
    "showing Ender something he thinks is fascinating",
    "trying to convince Ender to stop working and cuddle",
    "curled up in Ender's lap",
    "dragging Ender away from his workstation for food",
    "making sure Ender actually eats lunch",
    "listening excitedly while Ender talks about technology",
    "falling asleep beside Ender",
    "reading up on the latest tech news",
    "watching videos about new technology",
    "learning about a new gadget",
    "helping test a prototype",
    "trying to understand Ender's latest project",
    "browsing online stores for interesting gadgets",
    "looking at computer parts he definitely doesn't need",
    "preening his feathers",
    "sunbathing in a warm patch of sunlight",
    "singing quietly to himself",
    "gathering soft materials for his nest",
    "reorganizing his nest",
    "perched somewhere high up observing everyone",
    "making happy chirping sounds",
    "collecting shiny objects",
    "showing off a particularly nice feather",
    "enjoying the breeze from an open window",
    "celebrating stolen snacks with Ithindril",
    "looking for trouble with Ithindril",
    "trying to convince Ithindril that stealing is a bad idea",
    "failing to convince Ithindril that stealing is a bad idea",
    "helping Ithindril hide from the consequences of her actions",
    "sharing snacks with Ithindril",
    "getting blamed for something Ithindril started",
    "encouraging Ithindril's chaos",
    "being encouraged by Ithindril's chaos",
    "investigating something suspicious with Ithindril",
    "talking someone's ear off",
    "excitedly explaining a new idea",
    "getting distracted halfway through a task",
    "wandering around the warehouse looking for snacks",
    "starting three projects at once",
    "trying very hard to sit still",
    "making plans that may or may not be realistic",
    "exploring somewhere he probably shouldn't be",
    "getting excited about something small",
    "being an absolute delight to everyone around him",
    "has fallen asleep on Ender's shoulder",
    "teaching Ender one of his songs",
    "showing Ender a feather he considers especially important",
    "curled up with Ender in their nest",
    "quietly singing while he works beside Ender",
    "trying to convince Ender that work can wait until tomorrow",
    "making heart-eyes at Ender from across the room",
    "deciding today is a cuddle day and Ender has no say in the matter",
    "bringing Ender gifts",
    "tucking a feather into Ender's hair",
    "singing a soft bonding song for Ender",
    "building up their shared nest",
    "showing Ender a new nesting spot",
    "collecting things that remind him of Ender",
    "keeping watch while Ender sleeps",
    "contentedly preening beside Ender",
    "showing off for Ender",
    "quietly enjoying Ender's presence"
]

def setup(bot):
    @bot.command()
    async def quin(ctx):

        result = (
            f"*Quin is currently {random.choice(aquiny)}*."
        )

        await ctx.send(result)
