import random

sevka = [
    "making another batch of drugs",
    "making an experimental potion",
    "resting in his tank, his beautiful scales shimmering in the biolumenescent lighting",
    "carefully documenting his latest findings",
    "analyzing a strange magical sample",
    "reviewing research notes",
    "testing a new medicinal formula",
    "studying a rare magical disease",
    "working on a long-term research project",
    "cataloguing unusual specimens",
    "investigating an unusual magical reaction",
    "comparing potion results",
    "researching a cure for a rare condition",
    "brewing a complex potion",
    "carefully measuring ingredients",
    "staring at a bubbling flask",
    "making healing tonics",
    "attempting to stabilize a volatile mixture",
    "organizing his potion ingredients",
    "experimenting with a new formula",
    "creating emergency medical supplies",
    "working with herbs and magical reagents",
    "trying to figure out why a potion failed",
    "treating an injured magical creature",
    "checking on recovering patients",
    "performing a routine health check",
    "preparing medical supplies",
    "writing treatment notes",
    "monitoring a patient's recovery",
    "teaching first aid to the gang",
    "patching up someone's injuries",
    "making sure everyone is taking care of themselves",
    "quietly worrying about his patients",
    "examining a newly rescued creature",
    "floating peacefully in his tank",
    "drifting beneath the water's surface",
    "enjoying the quiet of his aquatic habitat",
    "cleaning his scales",
    "watching the warehouse through the glass of his tank",
    "resting beneath glowing aquatic plants",
    "swimming slow circles through the water",
    "collecting aquatic herbs",
    "listening to the sounds of flowing water",
    "relaxing in the warmth of the tank lights",
    "having a discussion with Ender about a project",
    "checking on Zevryn after a mission",
    "trying to stop Ashara from setting something on fire",
    "wondering what Silk is up to this time",
    "giving Quin a gentle reminder to eat properly",
    "watching Ithindril cause trouble",
    "sharing a quiet conversation with Nyx",
    "making sure everyone is healthy",
    "being dragged into someone else's chaos",
    "trying to keep the warehouse running smoothly",
    "running on far too little sleep",
    "forgetting when he last took a break",
    "staring blankly at a page of notes",
    "drinking something caffeinated",
    "trying to remember why he entered a room",
    "taking a rare moment to rest",
    "working through a mountain of paperwork",
    "promising himself he'll sleep after this project",
    "looking mildly concerned about his latest results",
    "trying very hard not to adopt another rescue",
    "putting out another fire Ashara started",
    "wondering why everyone keeps bringing him strange substances",
    "being used as free medical advice",
    "questioning the decisions that led him here",
    "explaining science to someone who immediately stopped listening",
    "trying to stop Ithindril from eating something dangerous",
    "finding glitter in a sample that definitely shouldn't contain glitter",
    "cleaning up after a successful experiment",
    "cleaning up after an unsuccessful experiment",
    "pretending everything is under control",
    "asleep in his tank after working for nearly two days straight",
    "has finally solved a problem that's been bothering him for weeks",
    "is watching over the warehouse while everyone else sleeps",
    "is allowing himself a rare moment of peace",
    "is staring at an experiment that should not be doing that",
    "is reflecting on old memories beneath the water's surface",
    "is smiling softly as he watches the gang interact",
    "is receiving strict instructions from everyone else to take a break"
]

def setup(bot):
    @bot.command()
    async def sev(ctx):

        result = (
            f"*Dr. Sevka is currently {random.choice(sevka)}*."
        )

        await ctx.send(result)
